version: '3.8'

networks:
    decalogue-network:

services:
    db:
        image: mongo:4.2.0
        container_name: speednotes
        networks:
            default:
            decalogue-network:
        volumes:
            - mongo-speednotes:/data/db
        ports:
            - 27017:27017
        restart: unless-stopped

volumes:
    mongo-speednotes:
